language: ruby
sudo: false
bundler_args: --without development
script: "bundle exec rake spec SPEC_OPTS='--color --format documentation'"
notifications:
  email: false
rvm:
  - 1.9.3
  - 1.8.7-p374
  - 2.0.0
  - 2.2.0
  - ruby-head
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
