sudo: false
language: ruby
cache:
  bundler: true
branches:
  only:
    - master
before_install:
  - gem update --system
  - gem install bundler
  - bundle install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
matrix:
  include:
    - rvm: 2.6
      script:
        - bundle exec rubocop
        - bundle exec rubycritic --no-browser -s 80 -f console
        - bundle exec rake spec

    - rvm: 2.5
      script:
        - bundle exec rake spec

    - rvm: 2.4
      script:
        - bundle exec rake spec

    - rvm: 2.3
      script:
        - bundle exec rake spec

    - rvm: jruby-head
      script:
        - bundle exec rake spec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
