version: 3.0.1.{build}
clone_depth: 10
install:
  - git submodule update --init --recursive

  - choco install mingw-w64 -y -Version 4.8.3 -source https://www.myget.org/F/puppetlabs
  - SET PATH=C:\Ruby21-x64\bin;C:\tools\mingw64\bin;%PATH%

  - ps: wget 'https://s3.amazonaws.com/kylo-pl-bucket/boost_1_57_0-x86_64_mingw-w64_4.8.3_win32_seh.7z' -OutFile "$pwd\boost.7z"
  - ps: 7z.exe x boost.7z -oC:\tools | FIND /V "ing  "

  - ps: wget 'https://s3.amazonaws.com/kylo-pl-bucket/yaml-cpp-0.5.1-x86_64_mingw-w64_4.8.3_win32_seh.7z' -OutFile "$pwd\yaml-cpp.7z"
  - ps: 7z.exe x yaml-cpp.7z -oC:\tools | FIND /V "ing  "

  - gem install bundler --quiet --no-ri --no-rdoc
  - bundle install --jobs 4 --retry 2 --gemfile=lib/Gemfile --quiet

build_script:
  - ps: mv "C:\Program Files (x86)\Git\bin\sh.exe" "C:\Program Files (x86)\Git\bin\shxx.exe"
  - ps: cmake -G "MinGW Makefiles" -DBOOST_ROOT="C:\tools\boost_1_57_0-x86_64_mingw-w64_4.8.3_win32_seh" -DYAMLCPP_ROOT="C:\tools\yaml-cpp-0.5.1-x86_64_mingw-w64_4.8.3_win32_seh" -DBOOST_STATIC=ON -DBOOST_NOWIDE_SKIP_TESTS=ON -DCMAKE_INSTALL_PREFIX="C:\Program Files\FACTER" .
  - ps: mv "C:\Program Files (x86)\Git\bin\shxx.exe" "C:\Program Files (x86)\Git\bin\sh.exe"
  - ps: mingw32-make -j2

test_script:
  - ps: ctest -V 2>&1 | %{ if ($_ -is [System.Management.Automation.ErrorRecord]) { $_ | c++filt } else { $_ } }
  - ps: mingw32-make install
