HOSTS:
  agent-centos-5-x86_64:
    roles:
      - agent
    platform: el-5-x86_64
    template: centos-5-x86_64
    hypervisor: vcloud
  agent-centos-5-i386:
    roles:
      - agent
    platform: el-5-i386
    template: centos-5-i386
    hypervisor: vcloud
CONFIG:
  datastore: instance0
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
