HOSTS:
  centos-55-64-1:
    roles:
      - master
      - database
      - agent
    platform: el-5-x86_64
    template: centos-5-x86_64
    hypervisor: vcloud
  centos-55-386-1:
    roles:
      - agent
    platform: el-5-i386
    template: centos-5-i386
    hypervisor: vcloud
CONFIG:
  nfs_server: none
  consoleport: 443
  datastore: instance0
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vcloud.delivery.puppetlabs.net/
