HOSTS:
  agent-fedora-19-x86_64:
    roles:
      - agent
    platform: fedora-19-x86_64
    template: fedora-19-x86_64
    hypervisor: vcloud
  agent-fedora-19-i386:
    roles:
      - agent
    platform: fedora-19-i386
    template: fedora-19-i386
    hypervisor: vcloud
CONFIG:
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
