HOSTS:
  agent-precise-x86_64:
    roles:
      - agent
    platform: ubuntu-precise-x86_64
    template: ubuntu-1204-x86_64
    hypervisor: vcloud
  agent-precise-i386:
    roles:
      - agent
    platform: ubuntu-precise-i386
    template: ubuntu-1204-i386
    hypervisor: vcloud
CONFIG:
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
