HOSTS:
  agent-rhel7-x86_64:
    roles:
      - agent
    platform: el-7-x86_64
    template: redhat-7-x86_64
    hypervisor: vcloud
CONFIG:
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
