HOSTS:
  agent-rhel6-x86_64:
    roles:
      - agent
    platform: el-6-x86_64
    template: redhat-6-x86_64
    hypervisor: vcloud
  agent-rhel6-i386:
    roles:
      - agent
    platform: el-6-i386
    template: redhat-6-i386
    hypervisor: vcloud
CONFIG:
  datastore: instance0
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
