HOSTS:
  agent-solaris-11-x86_64:
    roles:
      - agent
    platform: solaris-11-x86_64
    template: solaris-11-x86_64
    hypervisor: vcloud
CONFIG:
  datastore: instance0
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
