HOSTS:
  agent-squeeze-x86_64:
    roles:
      - agent
    platform: debian-squeeze-x86_64
    template: debian-6-x86_64
    hypervisor: vcloud
  agent-squeeze-i386:
    roles:
      - agent
    platform: debian-squeeze-i386
    template: debian-6-i386
    hypervisor: vcloud
CONFIG:
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
