HOSTS:
  agent-wheezy-x86_64:
    roles:
      - agent
    platform: debian-wheezy-x86_64
    template: debian-7-x86_64
    hypervisor: vcloud
  agent-wheezy-i386:
    roles:
      - agent
    platform: debian-wheezy-i386
    template: debian-7-i386
    hypervisor: vcloud
CONFIG:
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
