HOSTS:
  agent-2008r2-x86_64:
    roles:
      - agent
    platform: windows-2008r2-64
    ruby_arch: x86
    hypervisor: vcloud
    template: Delivery/Quality Assurance/Templates/vCloud/win-2008r2-x86_64
CONFIG:
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
