HOSTS:
  centos-6-x86_64:
    roles:
      - master
      - database
      - agent
      - dashboard
    platform: el-6-x86_64
    hypervisor: vcloud
    template: centos-6-x86_64
  win2003-32:
    roles:
      - agent
    platform: windows-2003-32
    hypervisor: vcloud
    template: win-2003-i386
CONFIG:
  nfs_server: NONE
  consoleport: 443
  datastore: instance0
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vcloud.delivery.puppetlabs.net/
