---
name: Integration tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: true

jobs:
  integration_tests:
    name: integration ${{ matrix.cfg.os }} (ruby ${{ matrix.cfg.ruby }})
    strategy:
      matrix:
        cfg:
          - {os: ubuntu-latest, ruby: '2.7'}
          - {os: ubuntu-22.04, ruby: '3.2'} # with openssl 3
          - {os: ubuntu-22.04, ruby: 'jruby-9.3.14.0'}
          - {os: ubuntu-latest, ruby: 'jruby-9.4.8.0'}
          - {os: windows-2022, ruby: '2.7'}
          - {os: windows-2022, ruby: '3.2'} # with openssl 3
    runs-on: ${{ matrix.cfg.os }}
    env:
      BUNDLE_SET: 'with integration'
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v4

      - name: Rspec checks
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.cfg.ruby }}
          bundler-cache: true
      - run: bundle exec rake spec_integration
