---
name: Snyk Monitor
on:
  push:
    branches:
      - main
jobs:
  snyk_monitor:
    if: ${{ github.repository_owner == 'puppetlabs' }}
    runs-on: ubuntu-20.04
    name: Snyk Monitor
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install dependencies
        run: bundle install --jobs 3 --retry 3
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/ruby@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_FOSS_KEY }}
        with:
          command: monitor
          args: --org=puppet-foss --project-name=${{ github.repository }}
